#!/bin/bash

MYSQL_PWD=$DATABASE_ROOT_PASSWORD mysql -u root <<EOF
CREATE DATABASE IF NOT EXISTS $DATABASE;
CREATE USER IF NOT EXISTS '$DATABASE_USER'@'%' IDENTIFIED BY '$DATABASE_PASSWORD';
GRANT ALL PRIVILEGES ON wordpress.* TO '$DATABASE_USER'@'%';
ALTER USER 'root'@'localhost' IDENTIFIED BY '$DATABASE_ROOT_PASSWORD';
FLUSH PRIVILEGES;
EOF

mysqladmin -u root -p$DATABASE_ROOT_PASSWORD shutdown
